spring:
  datasource:
    url: jdbc:mysql://localhost:3306/to_do_list?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "011006"
mybatis:
  type-aliases-package: com.meng.todolist.entity
  mapper-locations: classpath:/mappers/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8080